dist: xenial
sudo: false

language: c
compiler: clang
cache: ccache

env:
  global:
    - CC=clang
    - CXX=clang++
    - CFLAGS=-fsanitize=fuzzer,address
    - CXXFLAGS=-fsanitize=fuzzer,address
    - LIB_FUZZING_ENGINE=-fsanitize=fuzzer
  matrix:
    - FUZZER=filters_fuzzer
    - FUZZER=lzma2dec_fuzzer
    - FUZZER=lzma2enc_fuzzer
    - FUZZER=lzmadec_fuzzer
    - FUZZER=lzmaenc_fuzzer

script:
  - make
  - |
    [ ! -d "corpus/$FUZZER" ] || ./$FUZZER corpus/$FUZZER/*
  - ./$FUZZER -max_total_time=10
