dist: xenial
sudo: false

language: c
compiler: clang
cache: ccache

env:
  global:
    - CC=clang
    - CXX=clang++
    - CFLAGS=-fsanitize=fuzzer,address
    - CXXFLAGS=-fsanitize=fuzzer,address
    - LIB_FUZZING_ENGINE=-fsanitize=fuzzer
  matrix:
    - FUZZER=check-sdk
    - FUZZER=7z_fuzzer
    - FUZZER=filters_fuzzer
    - FUZZER=lzma2dec_fuzzer
    - FUZZER=lzma2enc_fuzzer
    - FUZZER=lzmadec_fuzzer
    - FUZZER=lzmaenc_fuzzer
    - FUZZER=ppmdenc_fuzzer
    - FUZZER=xzdec_fuzzer
    - FUZZER=xzenc_fuzzer

script:
  - ./scripts/run-travis.sh
